### ISSUE TITLE
Add redux-persist for offline mode

### ISSUE THREAD

**Issue by klapperkopp** [VeritasDev/BattleBuddy#11]
https://github.com/rt2zz/redux-persist can be used to save the redux state offline in-browser and make offline mode possible.

**Comment by VeritasDev** [comment]
Does Firebase not provide this?

**Comment by klapperkopp** [comment]
If you save everything online in firebase what happens if the user is offline? You need to hold a local persistent copy of the settings (ads is maybe a bad example as in offline mode you wouldn't see any anyways). redux-persist has a good way of doing this.

This is of course just based on the assumption that there will be more user settings that should be synced to the cloud and/or locally saved in the future. :)

**Comment by jordykoppen** [comment]
Closing for now as It's no longer relevant.
