### ISSUE TITLE
Add firebase npm package for anon login and user settings

### ISSUE THREAD

**Issue by klapperkopp** [VeritasDev/BattleBuddy#12]
See https://firebase.google.com/docs/web/setup#node.js-apps for how to add.

Firebase Auth package will be used for anonymous user authentication and user settings/stats can be stored after auth. One example reducer and actions exist already for updating the status of enabled/disabled ads. See #10

**Comment by jordykoppen** [comment]
Closing for now as it's no longer relevant.
